pipeline {
    agent { label 'deployer-slave-amazon-linux' }
    options {
        timeout(time: 90, unit: 'MINUTES')
        timestamps()
    }
    stages {
        stage('Wait for Stack Ready') {
            steps {
                sh(script: 'aws cloudformation wait stack-update-complete --region eu-west-1 --stack-name HomeSite', returnStatus: true)
            }
        }
        stage('CDK Deploy') {
            steps {
                dir('cdk') {
                    sh '''
                    npm ci
                    npm test
                    npm run deploy
                    '''
                }
            }
        }
    }
    post { always { cleanWs() } }
}
